name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: bndynet/gh.flows/.github/workflows/npm.yml@main
    with:
      node-version: '24'           # default: '20'
      working-directory: '.'       # default: '.'
      registry-url: 'https://registry.npmjs.org' # default registry
      lint-command: 'npm run lint' # default: 'npm run lint'
      test-command: 'npm test'     # default: 'npm test'
      build-command: 'npm run build' # default: 'npm run build'
      publish-enabled: true        # default: false
      publish-auth-method: 'oidc'  # default: token (or oidc)
      publish-tag: 'latest'        # default: 'latest'
      publish-provenance: true     # default: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}   # when publish-enabled=true and publish-auth-method=token
